#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2006 (ita)

def build(bld):
	obj = bld.create_obj('cc', 'program')
	obj.source = 'asftest.c'
	obj.uselib_local = 'asflib'
	obj.target = 'asftest'

#def set_options(opt):
#	# options defined if src/ was to be compiled as a standalone module
#	opt.add_option('--meow', type='string', help='option hidden in the src module', dest='meow')

#def configure(conf):
#	print "sub-configuration file called (demo)"

