#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2006 (ita)

def build(bld):
	bld(features='c cshlib',
		source='''
		asf.c
		byteio.c
		data.c
		guid.c
		header.c
		parse.c
		''',
		ccflags='-DDEBUG -g -O0 -ansi -pedantic -Wall -Wextra -Wformat=2 -Wformat-nonliteral -Wformat-security -Wmissing-prototypes -Wstrict-prototypes -Wwrite-strings -fdiagnostics-show-option -Werror=implicit-function-declaration',
		target='asf',
		name='asflib',
	)

	bld.install_files('${PREFIX}/include', ['asf.h'])

#def set_options(opt):
#	# options defined if src/ was to be compiled as a standalone module
#	opt.add_option('--meow', type='string', help='option hidden in the src module', dest='meow')

#def configure(conf):
#	print "sub-configuration file called (demo)"

