#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2006 (ita)

def build(bld):
	obj = bld.create_obj('cc', 'shlib')
	obj.source='''
	asf.c
	byteio.c
	data.c
	guid.c
	header.c
	parse.c
	'''
	obj.ccflags='-DDEBUG -g -O0 -ansi -pedantic -Wall -Wextra'
	obj.target='asf'
	obj.name='asflib'

	install_files('PREFIX', 'include', 'asf.h')

#def set_options(opt):
#	# options defined if src/ was to be compiled as a standalone module
#	opt.add_option('--meow', type='string', help='option hidden in the src module', dest='meow')

#def configure(conf):
#	print "sub-configuration file called (demo)"

